name: zklogin_dart
description: Sui zkLogin Dart SDK.
version: 0.0.5
homepage: https://github.com/mofalabs/zklogin

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  poseidon: ^0.0.1
  sui_dart:
    path: ../../Scallop/sui-dart
  test: ^1.26.3

dev_dependencies:
  dio: ^5.1.2
